---
- name: Install amazon-cloudwatch-agent
  package:
    name: amazon-cloudwatch-agent
    state: present

- name: Create directory for CloudWatch config
  file:
    path: "{{ cloudwatch_agent_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy CloudWatch Agent configuration
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: "{{ cloudwatch_agent_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart cloudwatch agent

- name: Start and enable CloudWatch Agent
  systemd:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes














